name = "ClimateSurrogates"
uuid = "1f034f64-1a41-4bc8-84dc-c8a33b032d87"
authors = ["ali-ramadhan <ali.hh.ramadhan@gmail.com>"]
version = "0.1.0"

[deps]
DiffEqFlux = "aae7a2af-3d4f-5e19-a356-7da93b79d9d0"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
Oceananigans = "9e8cae18-63c1-5223-a75c-80ca9d6e9a09"
