name = "WindMixing"
uuid = "2f025b53-51a1-4c83-af04-4abac6e2f799"
authors = ["Xky <xin.lee18@imperial.ac.uk>"]
version = "0.1.0"

[deps]
BSON = "fbb218c0-5317-5bc6-957e-2ee96dd4b1f0"
DiffEqSensitivity = "41bf760c-e81c-5289-8e54-58b1f1f8abe2"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
OceanParameterizations = "1f034f64-1a41-4bc8-84dc-c8a33b032d87"
Oceananigans = "9e8cae18-63c1-5223-a75c-80ca9d6e9a09"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
